/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.upf.view.dialog.validation;

import br.com.upf.beans.ClassElement;
import br.com.upf.beans.ClassModel;
import br.com.upf.beans.DiagramOfStateModel;
import br.com.upf.view.GraphEditor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GiordaniAntonio
 */
public class DiagramOfStatesValidation extends javax.swing.JDialog {

    /**
     *
     */
    private GraphEditor graphEditor;

    /**
     *
     */
    private DiagramOfStateModel diagramOfStateModel;

    /**
     *
     */
    private ClassElement classElement;

    /**
     *
     */
    private ClassModel classModel;

    /**
     *
     */
    private String yesUrlIcon = "/br/com/upf/images/yes.png";

    /**
     *
     */
    private String noUrlIcon = "/br/com/upf/images/no.png";

    /**
     *
     */
    private String noContentUrlIcon = "/br/com/upf/images/no_content.png";

    /**
     *
     */
    private Icon yesIcon = new ImageIcon(DiagramOfStatesValidation.class.getResource(yesUrlIcon));

    /**
     *
     */
    private Icon noIcon = new ImageIcon(DiagramOfStatesValidation.class.getResource(noUrlIcon));

    /**
     *
     */
    private Icon noContentIcon = new ImageIcon(DiagramOfStatesValidation.class.getResource(noContentUrlIcon));

    /**
     * Creates new form DiagramOfStatesValidation
     *
     * @param editor
     * @param element
     */
    public DiagramOfStatesValidation(GraphEditor editor, ClassElement element) {
        super(editor, true);
        this.graphEditor = editor;
        this.classElement = element;
        this.classModel = classElement.getClassModel();
        this.diagramOfStateModel = classModel.getDiagramOfStateModel();
        initComponents();
        updateTitle();
        submitValidation();
    }

    private void updateTitle() {
        this.setTitle("Validação - Diagrama de Estados");
    }

    private void submitValidation() {
        // Estado inicial
        if (diagramOfStateModel.isContainsInitialState()) {
            jLabelStatusOne.setIcon(yesIcon);
        } else {
            jLabelStatusOne.setIcon(noIcon);
        }
        // Estados internos
        if (diagramOfStateModel.isContainsInternalStates()) {
            jLabelStatusTwo.setIcon(yesIcon);
        } else {
            jLabelStatusTwo.setIcon(noIcon);
        }

        // Estado final e transição final
        if (diagramOfStateModel.isContainsFinalStates()) {

            if (diagramOfStateModel.isContainsFinalStates()) {
                jLabelStatusThree.setIcon(yesIcon);
            } else {
                jLabelStatusThree.setIcon(noIcon);
            }

            // Transição final
            if (diagramOfStateModel.isContainsFinalTransitions()) {
                jLabelStatusSix.setIcon(yesIcon);
            } else {
                jLabelStatusSix.setIcon(noIcon);
            }
        } else {
            jLabelStatusThree.setIcon(noContentIcon);
            jLabelStatusSix.setIcon(noContentIcon);
        }

        // Transição Inicial
        if (diagramOfStateModel.isContainsInitialTransition()) {
            jLabelStatusFour.setIcon(yesIcon);
        } else {
            jLabelStatusFour.setIcon(noIcon);
        }

        // Transições internas
        if (diagramOfStateModel.isContainsInternalTransitions()) {
            jLabelStatusFive.setIcon(yesIcon);
        } else {
            jLabelStatusFive.setIcon(noIcon);
        }

        // Nome dos estados
        if (diagramOfStateModel.isCheckValidStatesName() && diagramOfStateModel.isCheckUniqueStatesName()) {
            jLabelStatusSeven.setIcon(yesIcon);
        } else {
            jLabelStatusSeven.setIcon(noIcon);
        }

        // Nome das trasições
        if (diagramOfStateModel.isCheckValidTransitionsName() && diagramOfStateModel.isCheckUniqueTransitionsName()) {
            jLabelStatusEight.setIcon(yesIcon);
        } else {
            jLabelStatusEight.setIcon(noIcon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jPanelValidationTitles = new javax.swing.JPanel();
        jPanelTitleOrder = new javax.swing.JPanel();
        jLabelTitleOrder = new javax.swing.JLabel();
        jPanelTitleDescription = new javax.swing.JPanel();
        jLabelTitleDescription = new javax.swing.JLabel();
        jPanelTitleStatus = new javax.swing.JPanel();
        jLabelTitleStatus = new javax.swing.JLabel();
        jPanelValidationApresentation = new javax.swing.JPanel();
        jPanelOrder = new javax.swing.JPanel();
        jLabelOrderOne = new javax.swing.JLabel();
        jLabelOrderTwo = new javax.swing.JLabel();
        jLabelOrderThree = new javax.swing.JLabel();
        jLabelOrderFour = new javax.swing.JLabel();
        jLabelOrderFive = new javax.swing.JLabel();
        jLabelOrderSix = new javax.swing.JLabel();
        jLabelOrderSeven = new javax.swing.JLabel();
        jLabelOrderEight = new javax.swing.JLabel();
        jPanelDescription = new javax.swing.JPanel();
        jLabelDescriptionOne = new javax.swing.JLabel();
        jLabelDescriptionTwo = new javax.swing.JLabel();
        jLabelDescriptionThree = new javax.swing.JLabel();
        jLabelDescriptionFour = new javax.swing.JLabel();
        jLabelDescriptionFive = new javax.swing.JLabel();
        jLabelDescriptionSix = new javax.swing.JLabel();
        jLabelDescriptionSeven = new javax.swing.JLabel();
        jLabelDescriptionEight = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatusOne = new javax.swing.JLabel();
        jLabelStatusTwo = new javax.swing.JLabel();
        jLabelStatusThree = new javax.swing.JLabel();
        jLabelStatusFour = new javax.swing.JLabel();
        jLabelStatusFive = new javax.swing.JLabel();
        jLabelStatusSix = new javax.swing.JLabel();
        jLabelStatusSeven = new javax.swing.JLabel();
        jLabelStatusEight = new javax.swing.JLabel();
        jPanelSouth = new javax.swing.JPanel();
        jPanelValidationRules = new javax.swing.JPanel();
        jScrollPaneValidationRules = new javax.swing.JScrollPane();
        jTextAreaValidationRules = new javax.swing.JTextArea();
        jPanelValidationControl = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Validação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanelValidationTitles.setPreferredSize(new java.awt.Dimension(800, 45));
        jPanelValidationTitles.setLayout(new java.awt.BorderLayout());

        jPanelTitleOrder.setPreferredSize(new java.awt.Dimension(75, 40));
        jPanelTitleOrder.setRequestFocusEnabled(false);
        jPanelTitleOrder.setLayout(new java.awt.BorderLayout());

        jLabelTitleOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitleOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleOrder.setText("Ordem");
        jPanelTitleOrder.add(jLabelTitleOrder, java.awt.BorderLayout.CENTER);

        jPanelValidationTitles.add(jPanelTitleOrder, java.awt.BorderLayout.LINE_START);

        jPanelTitleDescription.setPreferredSize(new java.awt.Dimension(600, 750));
        jPanelTitleDescription.setLayout(new java.awt.BorderLayout());

        jLabelTitleDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitleDescription.setText("  Descrição");
        jPanelTitleDescription.add(jLabelTitleDescription, java.awt.BorderLayout.CENTER);

        jPanelValidationTitles.add(jPanelTitleDescription, java.awt.BorderLayout.CENTER);

        jPanelTitleStatus.setPreferredSize(new java.awt.Dimension(125, 40));
        jPanelTitleStatus.setLayout(new java.awt.BorderLayout());

        jLabelTitleStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitleStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleStatus.setText("Status");
        jPanelTitleStatus.add(jLabelTitleStatus, java.awt.BorderLayout.CENTER);

        jPanelValidationTitles.add(jPanelTitleStatus, java.awt.BorderLayout.LINE_END);

        jPanelCenter.add(jPanelValidationTitles, java.awt.BorderLayout.NORTH);

        jPanelValidationApresentation.setLayout(new java.awt.BorderLayout());

        jPanelOrder.setPreferredSize(new java.awt.Dimension(75, 315));
        jPanelOrder.setLayout(new java.awt.GridLayout(8, 1));

        jLabelOrderOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderOne.setText("1");
        jPanelOrder.add(jLabelOrderOne);

        jLabelOrderTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderTwo.setText("2");
        jPanelOrder.add(jLabelOrderTwo);

        jLabelOrderThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderThree.setText("3");
        jPanelOrder.add(jLabelOrderThree);

        jLabelOrderFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderFour.setText("4");
        jPanelOrder.add(jLabelOrderFour);

        jLabelOrderFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderFive.setText("5");
        jPanelOrder.add(jLabelOrderFive);

        jLabelOrderSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderSix.setText("6");
        jPanelOrder.add(jLabelOrderSix);

        jLabelOrderSeven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderSeven.setText("7");
        jPanelOrder.add(jLabelOrderSeven);

        jLabelOrderEight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrderEight.setText("8");
        jPanelOrder.add(jLabelOrderEight);

        jPanelValidationApresentation.add(jPanelOrder, java.awt.BorderLayout.WEST);

        jPanelDescription.setLayout(new java.awt.GridLayout(8, 1));

        jLabelDescriptionOne.setText("Estado Inicial; Somente um; Obrigatório.");
        jPanelDescription.add(jLabelDescriptionOne);

        jLabelDescriptionTwo.setText("Estados Internos; No mínimo dóis; Obrigatório.");
        jPanelDescription.add(jLabelDescriptionTwo);

        jLabelDescriptionThree.setText("Estado Final; Zero ou mais; Opcional.");
        jPanelDescription.add(jLabelDescriptionThree);

        jLabelDescriptionFour.setText("Transição Inicial; Somente uma; Obrigatória.");
        jPanelDescription.add(jLabelDescriptionFour);

        jLabelDescriptionFive.setText("Transições Internas; No mínimo duas por estado, uma origem e outra destino; Obrigatório.");
        jPanelDescription.add(jLabelDescriptionFive);

        jLabelDescriptionSix.setText("Transição Final; Uma para cada estado final; Opcional.");
        jPanelDescription.add(jLabelDescriptionSix);

        jLabelDescriptionSeven.setText("Nome dos Estados; Válidos e únicos; Obrigatório.");
        jPanelDescription.add(jLabelDescriptionSeven);

        jLabelDescriptionEight.setText("Nome das Transições; válidos; Obrigatório.");
        jPanelDescription.add(jLabelDescriptionEight);

        jPanelValidationApresentation.add(jPanelDescription, java.awt.BorderLayout.CENTER);

        jPanelStatus.setPreferredSize(new java.awt.Dimension(125, 315));
        jPanelStatus.setLayout(new java.awt.GridLayout(8, 1));

        jLabelStatusOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusOne);

        jLabelStatusTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusTwo);

        jLabelStatusThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusThree);

        jLabelStatusFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusFour);

        jLabelStatusFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusFive);

        jLabelStatusSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusSix);

        jLabelStatusSeven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusSeven);

        jLabelStatusEight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelStatus.add(jLabelStatusEight);

        jPanelValidationApresentation.add(jPanelStatus, java.awt.BorderLayout.EAST);

        jPanelCenter.add(jPanelValidationApresentation, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(800, 155));
        jPanelSouth.setLayout(new java.awt.BorderLayout());

        jPanelValidationRules.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Regras de Validação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanelValidationRules.setLayout(new java.awt.BorderLayout());

        jScrollPaneValidationRules.setBorder(null);
        jScrollPaneValidationRules.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneValidationRules.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaValidationRules.setEditable(false);
        jTextAreaValidationRules.setColumns(20);
        jTextAreaValidationRules.setFont(new java.awt.Font("Monospaced", 2, 13)); // NOI18N
        jTextAreaValidationRules.setForeground(new java.awt.Color(102, 102, 102));
        jTextAreaValidationRules.setLineWrap(true);
        jTextAreaValidationRules.setRows(5);
        jTextAreaValidationRules.setText("Todos os requisitos listados acima devem válidos para o diagrama ser considerado válido.");
        jTextAreaValidationRules.setBorder(null);
        jTextAreaValidationRules.setOpaque(false);
        jScrollPaneValidationRules.setViewportView(jTextAreaValidationRules);

        jPanelValidationRules.add(jScrollPaneValidationRules, java.awt.BorderLayout.CENTER);

        jPanelSouth.add(jPanelValidationRules, java.awt.BorderLayout.CENTER);

        jPanelValidationControl.setPreferredSize(new java.awt.Dimension(800, 45));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExit.setText("Sair");
        jButtonExit.setPreferredSize(new java.awt.Dimension(150, 25));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelValidationControlLayout = new javax.swing.GroupLayout(jPanelValidationControl);
        jPanelValidationControl.setLayout(jPanelValidationControlLayout);
        jPanelValidationControlLayout.setHorizontalGroup(
            jPanelValidationControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelValidationControlLayout.createSequentialGroup()
                .addContainerGap(638, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelValidationControlLayout.setVerticalGroup(
            jPanelValidationControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValidationControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSouth.add(jPanelValidationControl, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 818, 592);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelDescriptionEight;
    private javax.swing.JLabel jLabelDescriptionFive;
    private javax.swing.JLabel jLabelDescriptionFour;
    private javax.swing.JLabel jLabelDescriptionOne;
    private javax.swing.JLabel jLabelDescriptionSeven;
    private javax.swing.JLabel jLabelDescriptionSix;
    private javax.swing.JLabel jLabelDescriptionThree;
    private javax.swing.JLabel jLabelDescriptionTwo;
    private javax.swing.JLabel jLabelOrderEight;
    private javax.swing.JLabel jLabelOrderFive;
    private javax.swing.JLabel jLabelOrderFour;
    private javax.swing.JLabel jLabelOrderOne;
    private javax.swing.JLabel jLabelOrderSeven;
    private javax.swing.JLabel jLabelOrderSix;
    private javax.swing.JLabel jLabelOrderThree;
    private javax.swing.JLabel jLabelOrderTwo;
    private javax.swing.JLabel jLabelStatusEight;
    private javax.swing.JLabel jLabelStatusFive;
    private javax.swing.JLabel jLabelStatusFour;
    private javax.swing.JLabel jLabelStatusOne;
    private javax.swing.JLabel jLabelStatusSeven;
    private javax.swing.JLabel jLabelStatusSix;
    private javax.swing.JLabel jLabelStatusThree;
    private javax.swing.JLabel jLabelStatusTwo;
    private javax.swing.JLabel jLabelTitleDescription;
    private javax.swing.JLabel jLabelTitleOrder;
    private javax.swing.JLabel jLabelTitleStatus;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelTitleDescription;
    private javax.swing.JPanel jPanelTitleOrder;
    private javax.swing.JPanel jPanelTitleStatus;
    private javax.swing.JPanel jPanelValidationApresentation;
    private javax.swing.JPanel jPanelValidationControl;
    private javax.swing.JPanel jPanelValidationRules;
    private javax.swing.JPanel jPanelValidationTitles;
    private javax.swing.JScrollPane jScrollPaneValidationRules;
    private javax.swing.JTextArea jTextAreaValidationRules;
    // End of variables declaration//GEN-END:variables
}
