/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.upf.view.dialog;

import br.com.upf.beans.Attribute;
import br.com.upf.beans.ClassModel;
import br.com.upf.view.GraphEditor;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.util.mxResources;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author GiordaniAntonio
 */
public class AttributeEdition extends javax.swing.JDialog {
    
    private static final long serialVersionUID = 8826957605795109101L;

    /**
     *
     */
    private GraphEditor graphEditor;

    /**
     *
     */
    private ClassModel classModel;

    /**
     * Atributo em Edição
     */
    private Attribute editingAttribute;

    /**
     *
     */
    private Attribute attribute;

    /**
     *
     */
    private boolean edition;

    /**
     * Creates new form EdicaoAtributoDialog
     *
     * @param editor
     * @param attribute
     * @param edition
     */
    public AttributeEdition(GraphEditor editor, ClassModel classModel, Attribute attribute, boolean edition) {
        super(editor, true);
        initComponents();
        updateTitle();
        this.graphEditor = editor;
        this.classModel = classModel;
        this.editingAttribute = attribute;
        this.edition = edition;
        
        if (this.edition) {
            if (editingAttribute != null) {
                viewValidationFields(false);
                jTextFieldName.setText(editingAttribute.getName());
                jComboBoxType.setSelectedItem(editingAttribute.getUmlType());
                jComboBoxVisibility.setSelectedItem(editingAttribute.getVisibility());
                jButtonAdd.setText("Salvar");
            } else {
                System.out.println("Atributo null");
            }
        } else {
            viewValidationFields(false);
        }
    }

    /**
     * Atualiza o titulo
     */
    private void updateTitle() {
        this.setTitle("Edição - Atributo");
    }

    /**
     * Controla a visualização dos campos de válidação
     *
     * @param value
     */
    private void viewValidationFields(boolean value) {
        jLabelNameInformation.setVisible(value);
        jLabelTypeInformation.setVisible(value);
        jLabelVisibilityInformation.setVisible(value);
    }

    /**
     * Valida os campos editaveis da expressão
     *
     * @return
     */
    private boolean validateAttributeEditing() {
        boolean validName, validType, validVisibility;
        
        viewValidationFields(false);

        // Validação - Nome
        if (!jTextFieldName.getText().isEmpty()) {
            validName = true;
        } else {
            jLabelNameInformation.setVisible(true);
            jTextFieldName.requestFocus();
            validName = false;
        }

        // Validação - Tipo
        if (jComboBoxType.getSelectedIndex() != 0) {
            validType = true;
        } else {
            jLabelTypeInformation.setVisible(true);
            jComboBoxType.requestFocus();
            validType = false;
        }

        // Validação - Visibilidade
        if (jComboBoxVisibility.getSelectedIndex() != 0) {
            validVisibility = true;
        } else {
            jLabelVisibilityInformation.setVisible(true);
            jComboBoxVisibility.requestFocus();
            validVisibility = false;
        }
        
        return validName && validType && validVisibility;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanelCenter = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelVisibility = new javax.swing.JLabel();
        jComboBoxVisibility = new javax.swing.JComboBox();
        jComboBoxType = new javax.swing.JComboBox();
        jLabelNameInformation = new javax.swing.JLabel();
        jLabelTypeInformation = new javax.swing.JLabel();
        jLabelVisibilityInformation = new javax.swing.JLabel();
        jPanelSouth = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição de Atributo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelCenter.setPreferredSize(new java.awt.Dimension(256, 150));

        jTextFieldName.setToolTipText("Nome do Atributo");
        jTextFieldName.setNextFocusableComponent(jComboBoxType);
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jLabelName.setText("Nome:");

        jLabelType.setText("Tipo:");

        jLabelVisibility.setText("Visibilidade:");

        jComboBoxVisibility.setMaximumRowCount(4);
        jComboBoxVisibility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "public", "package", "protected", "private" }));
        jComboBoxVisibility.setSelectedIndex(1);
        jComboBoxVisibility.setToolTipText("Visibilidade do Atributo");
        jComboBoxVisibility.setNextFocusableComponent(jButtonAdd);
        jComboBoxVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVisibilityActionPerformed(evt);
            }
        });

        jComboBoxType.setMaximumRowCount(6);
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Boolean", "Double", "Float", "Integer", "String" }));
        jComboBoxType.setToolTipText("Tipo do Atributo");
        jComboBoxType.setNextFocusableComponent(jComboBoxVisibility);
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabelNameInformation.setForeground(new java.awt.Color(255, 102, 0));
        jLabelNameInformation.setText("Campo Obrigatório");
        jLabelNameInformation.setToolTipText("Informe o Nome!");

        jLabelTypeInformation.setForeground(new java.awt.Color(255, 102, 0));
        jLabelTypeInformation.setText("Campo Obrigatório");
        jLabelTypeInformation.setToolTipText("Selecione o Tipo!");

        jLabelVisibilityInformation.setForeground(new java.awt.Color(255, 102, 0));
        jLabelVisibilityInformation.setText("Campo Obrigatório");
        jLabelVisibilityInformation.setToolTipText("Selecione a Visibilidade!");

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCenterLayout.createSequentialGroup()
                        .addComponent(jLabelVisibility)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxVisibility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTypeInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVisibilityInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNameInformation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCenterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelName, jLabelType, jLabelVisibility});

        jPanelCenterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxType, jComboBoxVisibility, jTextFieldName});

        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTypeInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVisibilityInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelCenterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelNameInformation, jLabelTypeInformation, jLabelVisibilityInformation});

        jPanelCenterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelName, jLabelType, jLabelVisibility});

        jPanelCenterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxType, jComboBoxVisibility, jTextFieldName});

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(380, 45));

        jButtonAdd.setText("Adicionar");
        jButtonAdd.setNextFocusableComponent(jButtonCancel);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddjButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(65, 23));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(65, 23));
        jButtonCancel.setNextFocusableComponent(jTextFieldName);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(65, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanceljButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelSouthLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonCancel});

        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSouthLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAdd, jButtonCancel});

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 375, 212);
    }// </editor-fold>//GEN-END:initComponents

    // Codigo executado no fechamento da janela
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed

    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButtonCanceljButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanceljButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCanceljButtonCancelarActionPerformed

    private void jButtonAddjButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddjButtonAdicionarActionPerformed
        
        if (validateAttributeEditing()) {
            if (edition) {
                attribute = new Attribute();
                attribute.setName(jTextFieldName.getText());
                attribute.setUmlType((String) jComboBoxType.getSelectedItem());
                attribute.setVisibility(jComboBoxVisibility.getSelectedItem().toString());
                attribute.calculateResume();
                
                Integer index = classModel.getIndex(editingAttribute);
                if (classModel.checkUniquenessEdit(attribute, index)) {
                    classModel.editAttribute(attribute, index);
                    classModel.setUpdatedTableCode(false);
                    resetFields();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, mxResources.get("violationOfTheUniquenessRule"), mxResources.get("validation"), JOptionPane.WARNING_MESSAGE);
                }
            } else {
                editingAttribute = new Attribute();
                editingAttribute.setName(jTextFieldName.getText());
                editingAttribute.setUmlType((String) jComboBoxType.getSelectedItem());
                switch (jComboBoxType.getSelectedIndex()) {
                    case 1:
                        editingAttribute.setCharacterValue(true);
                        break;
                    case 2:
                        editingAttribute.setCharacterValue(false);
                        break;
                    case 3:
                        editingAttribute.setCharacterValue(false);
                        break;
                    case 4:
                        editingAttribute.setCharacterValue(false);
                        break;
                    case 5:
                        editingAttribute.setCharacterValue(true);
                        break;
                }
                editingAttribute.setVisibility(jComboBoxVisibility.getSelectedItem().toString());
                editingAttribute.calculateResume();
                
                if (classModel.checkUniquenessAdd(editingAttribute)) {
                    classModel.addAttribute(editingAttribute);
                    classModel.setUpdatedTableCode(false);
                    resetFields();
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, mxResources.get("violationOfTheUniquenessRule"), mxResources.get("validation"), JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonAddjButtonAdicionarActionPerformed

    private void jComboBoxVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVisibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVisibilityActionPerformed

    /**
     * veta a utilização de espaços no nome do atributo
     *
     * @param evt
     */
    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        char c = evt.getKeyChar();
        
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    /**
     * Reseta campos de edição
     */
    private void resetFields() {
        jTextFieldName.setText("");
        jComboBoxType.setSelectedIndex(0);
        jComboBoxVisibility.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JComboBox jComboBoxVisibility;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameInformation;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelTypeInformation;
    private javax.swing.JLabel jLabelVisibility;
    private javax.swing.JLabel jLabelVisibilityInformation;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

}
