/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.upf.view.dialog;

import br.com.upf.beans.ClassElement;
import br.com.upf.beans.ClassModel;
import br.com.upf.view.GraphEditor;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author GiordaniAntonio
 */
public class MethodElaborationDictionary extends javax.swing.JDialog {

    private static final long serialVersionUID = 8590567702433963592L;

    /**
     *
     */
    private GraphEditor graphEditor;

    /**
     *
     */
    private ClassElement classElement;

    /**
     *
     */
    private ClassModel classModel;

    /**
     * Creates new form MethodologyDevelopment
     *
     * @param editor
     * @param element
     */
    public MethodElaborationDictionary(GraphEditor editor, ClassElement element) {
        super(editor, true);
        this.graphEditor = editor;
        this.classElement = element;
        this.classModel = classElement.getClassModel();
        initComponents();
        if (classModel.isInitializedDictionaryOfStates()) {
            if (classModel.isMethodElaborationCustom()) {
                jComboBoxMethod.setSelectedIndex(2);
            }
            if (!classModel.isMethodElaborationCustom()) {
                jComboBoxMethod.setSelectedIndex(1);
            }
        }

        updateTitle();
    }

    private void updateTitle() {
        this.setTitle("Método - Dicionário de Estados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMethodology = new javax.swing.ButtonGroup();
        jPanelCenter = new javax.swing.JPanel();
        jPanelMethodSelection = new javax.swing.JPanel();
        jComboBoxMethod = new javax.swing.JComboBox();
        jLabelMethodElaboration = new javax.swing.JLabel();
        jPanelMethodInformation = new javax.swing.JPanel();
        jPanelSelectionMethod = new javax.swing.JPanel();
        jLabelSelectMethod = new javax.swing.JLabel();
        jPanelMethodStandart = new javax.swing.JPanel();
        jScrollPaneMethodStandart = new javax.swing.JScrollPane();
        jTextAreaMethodStandart = new javax.swing.JTextArea();
        jPanelMethodCustom = new javax.swing.JPanel();
        jScrollPaneMethodCustom = new javax.swing.JScrollPane();
        jTextAreaMethodCustom = new javax.swing.JTextArea();
        jPanelSouth = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanelMethodSelection.setPreferredSize(new java.awt.Dimension(345, 50));

        jComboBoxMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Básico", "Avançado" }));
        jComboBoxMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMethodActionPerformed(evt);
            }
        });

        jLabelMethodElaboration.setText("Método de Elaboração:");

        javax.swing.GroupLayout jPanelMethodSelectionLayout = new javax.swing.GroupLayout(jPanelMethodSelection);
        jPanelMethodSelection.setLayout(jPanelMethodSelectionLayout);
        jPanelMethodSelectionLayout.setHorizontalGroup(
            jPanelMethodSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMethodSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMethodElaboration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanelMethodSelectionLayout.setVerticalGroup(
            jPanelMethodSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMethodSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMethodSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMethodElaboration, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCenter.add(jPanelMethodSelection, java.awt.BorderLayout.NORTH);

        jPanelMethodInformation.setLayout(new java.awt.CardLayout());

        jPanelSelectionMethod.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSelectMethod.setForeground(new java.awt.Color(153, 153, 153));
        jLabelSelectMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSelectMethod.setText("Selecione o método de elaboração!");

        javax.swing.GroupLayout jPanelSelectionMethodLayout = new javax.swing.GroupLayout(jPanelSelectionMethod);
        jPanelSelectionMethod.setLayout(jPanelSelectionMethodLayout);
        jPanelSelectionMethodLayout.setHorizontalGroup(
            jPanelSelectionMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectionMethodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSelectMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSelectionMethodLayout.setVerticalGroup(
            jPanelSelectionMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSelectMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMethodInformation.add(jPanelSelectionMethod, "card0");

        jPanelMethodStandart.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneMethodStandart.setBorder(null);
        jScrollPaneMethodStandart.setOpaque(false);

        jTextAreaMethodStandart.setEditable(false);
        jTextAreaMethodStandart.setColumns(20);
        jTextAreaMethodStandart.setRows(5);
        jTextAreaMethodStandart.setText("O método de elaboração STANDART é utilizado para elaborar \nexpressões simples, em situações em que uma única \nexpressão é suficiente para representar o atributo em \ndeterminado estado.");
        jScrollPaneMethodStandart.setViewportView(jTextAreaMethodStandart);

        javax.swing.GroupLayout jPanelMethodStandartLayout = new javax.swing.GroupLayout(jPanelMethodStandart);
        jPanelMethodStandart.setLayout(jPanelMethodStandartLayout);
        jPanelMethodStandartLayout.setHorizontalGroup(
            jPanelMethodStandartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMethodStandartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneMethodStandart, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMethodStandartLayout.setVerticalGroup(
            jPanelMethodStandartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneMethodStandart, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMethodInformation.add(jPanelMethodStandart, "card1");

        jPanelMethodCustom.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneMethodCustom.setBorder(null);
        jScrollPaneMethodCustom.setOpaque(false);

        jTextAreaMethodCustom.setColumns(20);
        jTextAreaMethodCustom.setRows(5);
        jTextAreaMethodCustom.setText("O método de elaboração CUSTOM é utilizado para elaborar \nexpressões complexas, permitindo o uso de operadores \nlógicos entre outros recursos avançados para representar \nfaixas e combinações de valores.");
        jScrollPaneMethodCustom.setViewportView(jTextAreaMethodCustom);

        javax.swing.GroupLayout jPanelMethodCustomLayout = new javax.swing.GroupLayout(jPanelMethodCustom);
        jPanelMethodCustom.setLayout(jPanelMethodCustomLayout);
        jPanelMethodCustomLayout.setHorizontalGroup(
            jPanelMethodCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMethodCustomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneMethodCustom, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMethodCustomLayout.setVerticalGroup(
            jPanelMethodCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneMethodCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMethodInformation.add(jPanelMethodCustom, "card2");

        jPanelCenter.add(jPanelMethodInformation, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(325, 45));

        jButtonSave.setText("Salvar");
        jButtonSave.setToolTipText("Salvar e prosseguir");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 518, 297);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação do JComboBox - Seleção de Método de elaboração
     *
     * @param evt
     */
    private void jComboBoxMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMethodActionPerformed
        Integer selectIndexMethod = jComboBoxMethod.getSelectedIndex();
        CardLayout buildPanel = (CardLayout) jPanelMethodInformation.getLayout();

        switch (selectIndexMethod) {
            case 1:
                buildPanel.show(jPanelMethodInformation, "card1");
                break;
            case 2:
                buildPanel.show(jPanelMethodInformation, "card2");
                break;

            default:
                buildPanel.show(jPanelMethodInformation, "card0");
        }

    }//GEN-LAST:event_jComboBoxMethodActionPerformed

    /**
     * Ação do Botão - Cancelar
     *
     * @param evt
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Ação do Botão - Salvar
     *
     * @param evt
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        Integer selectIndexMethod = jComboBoxMethod.getSelectedIndex();
        if (selectIndexMethod != 0) {
            switch (selectIndexMethod) {
                case 1:
                    classModel.setMethodElaborationCustom(false);
                    break;
                case 2:
                    classModel.setMethodElaborationCustom(true);
                    break;
            }
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o Método de Elaboração!");
            jComboBoxMethod.requestFocus();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMethodology;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxMethod;
    private javax.swing.JLabel jLabelMethodElaboration;
    private javax.swing.JLabel jLabelSelectMethod;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelMethodCustom;
    private javax.swing.JPanel jPanelMethodInformation;
    private javax.swing.JPanel jPanelMethodSelection;
    private javax.swing.JPanel jPanelMethodStandart;
    private javax.swing.JPanel jPanelSelectionMethod;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPaneMethodCustom;
    private javax.swing.JScrollPane jScrollPaneMethodStandart;
    private javax.swing.JTextArea jTextAreaMethodCustom;
    private javax.swing.JTextArea jTextAreaMethodStandart;
    // End of variables declaration//GEN-END:variables
}
