/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.upf.view.dialog;

import br.com.upf.beans.ClassElement;
import br.com.upf.beans.ClassModel;
import br.com.upf.view.GraphEditor;

/**
 *
 * @author GiordaniAntonio
 */
public class TableCodeView extends javax.swing.JDialog {

    private static final long serialVersionUID = 5827907660442298031L;

    private GraphEditor graphEditor;

    private ClassElement classElement;

    private ClassModel classModel;

    /**
     * Creates new form TableView
     *
     * @param editor
     * @param element
     */
    public TableCodeView(GraphEditor editor, ClassElement element) {
        super(editor, true);
        initComponents();
        this.graphEditor = editor;
        this.classElement = element;
        this.classModel = classElement.getClassModel();

        displayTableCode();
        updateTitle();
    }
    
    private void updateTitle() {
        this.setTitle("Código da Tabela");
    }

    /**
     * Exibe no painel o Código da Tabela
     */
    private void displayTableCode() {
        jTextAreaTable.setText(classModel.getTableCode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTextAreaTable = new javax.swing.JTextArea();
        jPanelSouth = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jTextAreaTable.setEditable(false);
        jTextAreaTable.setColumns(20);
        jTextAreaTable.setRows(5);
        jScrollPaneTable.setViewportView(jTextAreaTable);

        jPanelCenter.add(jScrollPaneTable, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(850, 45));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExit.setText("Sair");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        setBounds(0, 0, 818, 492);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTextArea jTextAreaTable;
    // End of variables declaration//GEN-END:variables
}
