/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.upf.view.dialog;

import br.com.upf.beans.ClassElement;
import br.com.upf.beans.ClassModel;
import br.com.upf.view.GraphEditor;

/**
 *
 * @author GiordaniAntonio
 */
public class TriggersCodeView extends javax.swing.JDialog {

    private static final long serialVersionUID = 5827907660442298031L;

    private GraphEditor graphEditor;

    private ClassElement classElement;

    private ClassModel classModel;

    /**
     * Creates new form TableView
     *
     * @param editor
     * @param element
     */
    public TriggersCodeView(GraphEditor editor, ClassElement element) {
        super(editor, true);
        initComponents();
        this.graphEditor = editor;
        this.classElement = element;
        this.classModel = classElement.getClassModel();

        updateTitle();
        triggersCodeView();
    }

    private void updateTitle() {
        this.setTitle("Código dos Gatilhos");
    }

    private void triggersCodeView() {
        jTextAreaTriggers.setText(classModel.getTriggersCode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jScrollPaneTriggers = new javax.swing.JScrollPane();
        jTextAreaTriggers = new javax.swing.JTextArea();
        jPanelSouth = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonElaborationDictionaryOfStates = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jTextAreaTriggers.setColumns(20);
        jTextAreaTriggers.setRows(5);
        jScrollPaneTriggers.setViewportView(jTextAreaTriggers);

        jPanelCenter.add(jScrollPaneTriggers, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSouth.setPreferredSize(new java.awt.Dimension(850, 45));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExit.setText("Sair");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonElaborationDictionaryOfStates.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonElaborationDictionaryOfStates.setText("Dicionário de Estados");
        jButtonElaborationDictionaryOfStates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonElaborationDictionaryOfStatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(jButtonElaborationDictionaryOfStates, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        jPanelSouthLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonElaborationDictionaryOfStates, jButtonExit});

        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonElaborationDictionaryOfStates))
                .addContainerGap())
        );

        jButtonExit.getAccessibleContext().setAccessibleName("175");

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        setBounds(0, 0, 818, 492);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonElaborationDictionaryOfStatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElaborationDictionaryOfStatesActionPerformed
        this.setVisible(false);
        if (classModel.isMethodElaborationCustom()) {
            graphEditor.dictionaryOfStatesMethodCustomView(classElement);
        } else {
            graphEditor.dictionaryOfStatesMethodStandartView(classElement);
        }
    }//GEN-LAST:event_jButtonElaborationDictionaryOfStatesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonElaborationDictionaryOfStates;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPaneTriggers;
    private javax.swing.JTextArea jTextAreaTriggers;
    // End of variables declaration//GEN-END:variables
}
